[versions]
# https://fabricmc.net/develop/
fabric-loom = "1.17.+"
# https://projects.neoforged.net/neoforged/moddevgradle
moddevgradle = "2.0.141"
# https://codeberg.org/stonecutter/fletching-table/src/branch/main/build.gradle.kts#L18
fletching-table = "0.1.0-alpha.22"
# https://stonecutter.kikugie.dev/
stonecutter = "0.9.+"
# https://github.com/GradleUp/shadow/releases
shadow = "9.4.0"
# https://github.com/modmuss50/mod-publish-plugin/blob/main/build.gradle.kts#L13
mod-publish = "1.1.0"

minecraft-standalone = "26.2" # The MC version for the standalone JAR
datafixerupper = "9.0.19" # When updating MC for standalone, make sure to bump this too!

# https://github.com/FabricMC/Mixin/blob/main/gradle.properties#L7
mixin = "0.8.7"
# https://github.com/LlamaLad7/MixinExtras/releases
mixinextras = "0.5.4"

# https://fabricmc.net/develop/
fabric-loader = "0.19.3"
# https://modrinth.com/mod/fabric-language-kotlin/versions
fabric-kotlin = "1.13.12+kotlin.2.4.0"

# https://modrinth.com/mod/kotlin-lang-forge/versions
kotlinlangforge = "2.12.1-k2.4.0"

# https://kotlinlang.org/docs/releases.html
kotlin = "2.4.0"
kotlinx-coroutines = "1.11.0"
kotlinx-serialization = "1.11.0"

# https://www.slf4j.org/download.html
slf4j = "2.0.17"
# https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j
log4j = "2.25.4"
# https://github.com/Minecrell/TerminalConsoleAppender
terminalconsoleappender = "1.3.0"

# https://github.com/google/gson
gson = "2.14.0"

unitytranslatelib = "1.0.0"

# https://modrinth.com/mod/talk-balloons/versions
talk-balloons = "1.5.3"

# https://github.com/BluSpring/SunsetConfig/blob/main/build.gradle.kts#L23
sunset = "1.2.0"

# https://mvn.devos.one/#/snapshots/dev/cadindie/whisper4j
whisper4j = "1.0.0"

# https://maven.maxhenkel.de/#/releases/de/maxhenkel/voicechat/voicechat-api
voicechat-api = "2.6.13"

# https://plasmovoice.com/docs/api/
plasmo-api = "2.1.13"

# https://mvn.devos.one/#/releases/io/nayuki/flac-library-java
flac-java = "1.4.1"

# https://central.sonatype.com/artifact/io.github.ggerganov/whispercpp/versions
whispercpp = "1.4.0"

# https://github.com/java-native-access/jna/tags
jna = "5.19.1"

joml = "1.10.8"

# https://github.com/BloCamLimb/Arc3D
arc3d = "2026.2.0"
# https://github.com/BloCamLimb/ModernUI
modernui = "3.13.0"

[bundles]
kotlin = [
    "kotlinx-coroutines-core", "kotlinx-coroutines-core-jvm", "kotlinx-coroutines-jdk8", "kotlinx-serialization-json"
]
logging = [
    "slf4j-api", "slf4j-log4j",
    "log4j-api", "log4j-core",
    "terminalconsoleappender"
]
arc3d-api = [
    "arc3d-core", "arc3d-sketch",
]
arc3d-impl = [
    "arc3d-compiler", "arc3d-opengl",
    "arc3d-vulkan", "arc3d-granite", "arc3d-engine",
]
modernui = [
    "modernui-core", "modernui-ktx",
]

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
mixinextras-common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }
mixinextras-fabric = { module = "io.github.llamalad7:mixinextras-fabric", version.ref = "mixinextras" }
mixinextras-forge = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixinextras" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-log4j = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
terminalconsoleappender = { module = "net.minecrell:terminalconsoleappender", version.ref = "terminalconsoleappender" }

datafixerupper = { module = "com.mojang:datafixerupper", version.ref = "datafixerupper" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

unitytranslatelib = { module = "xyz.bluspring.unitytranslate:unitytranslate-library", version.ref = "unitytranslatelib" }
whispercpp = { module = "io.github.ggerganov:whispercpp", version.ref = "whispercpp" }

voicechat-api = { module = "de.maxhenkel.voicechat:voicechat-api", version.ref = "voicechat-api" }
plasmo-api-server = { module = "su.plo.voice.api:server", version.ref = "plasmo-api" }
plasmo-api-client = { module = "su.plo.voice.api:client", version.ref = "plasmo-api" }
sunset = { module = "xyz.bluspring.sunset:sunset-config", version.ref = "sunset" }

flac-java = { module = "io.nayuki:flac-library-java", version.ref = "flac-java" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }

joml = { module = "org.joml:joml", version.ref = "joml" }

arc3d-core = { module = "dev.icyllis:arc3d-core", version.ref = "arc3d" }
arc3d-compiler = { module = "dev.icyllis:arc3d-compiler", version.ref = "arc3d" }
arc3d-engine = { module = "dev.icyllis:arc3d-engine", version.ref = "arc3d" }
arc3d-granite = { module = "dev.icyllis:arc3d-granite", version.ref = "arc3d" }
arc3d-opengl = { module = "dev.icyllis:arc3d-opengl", version.ref = "arc3d" }
arc3d-sketch = { module = "dev.icyllis:arc3d-sketch", version.ref = "arc3d" }
arc3d-vulkan = { module = "dev.icyllis:arc3d-vulkan", version.ref = "arc3d" }

modernui-core = { module = "dev.icyllis:modernui-core", version.ref = "modernui" }
modernui-ktx = { module = "dev.icyllis:modernui-core-ktx", version.ref = "modernui" }

[plugins]
moddevgradle = { id = "net.neoforged.moddev" }
moddevgradle-legacy = { id = "net.neoforged.moddev.legacyforge" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
fletching-table = { id = "dev.kikugie.fletching-table", version.ref = "fletching-table" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
