modLoader="kotlinforforge"
loaderVersion="[4.7,)"
license="MIT"
issueTrackerURL="https://github.com/BluSpring/UnityTranslate/issues"

[[mods]]
    modId="unitytranslate"
    version="${version}"
    displayName="UnityTranslate"
    logoFile="icon.png"
    credits="Thanks to Argos Open Tech for creating LibreTranslate, without it this mod would not have been possible."
    authors="BluSpring"
    description='''
    A mod designed for free live translation, inspired by the QSMP. Mainly created for the Unity Multiplayer server, and for public release towards the multilingual Minecraft community.
    '''

[[dependencies.unitytranslate]]
    modId="neoforge"
    mandatory=true
    versionRange="[20.4,20.5)"
    ordering="NONE"
    side="BOTH"

[[dependencies.unitytranslate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4,1.20.5)"
    ordering="NONE"
    side="BOTH"

[[dependencies.unitytranslate]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="[${forge_kotlin_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.unitytranslate]]
    modId="architectury"
    mandatory=true
    versionRange="[${architectury_version},)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "unitytranslate.mixins.json"