name: Publish JDK 21 Mods
on:
  push:
    tags:
      - '*'
    branches:
      - 'ver/1.20.6'
      - 'ver/1.21.1'

jobs:
  build:
    name: Publish Versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true

      - name: Execute Gradle build
        run: ./gradlew publishModFiles